"""add branch id to employees

Revision ID: b38b5f3e6e65
Revises: ec7daa1e9812
Create Date: 2026-05-28 16:49:09.995512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38b5f3e6e65'
down_revision: Union[str, Sequence[str], None] = 'ec7daa1e9812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    # ### end Alembic commands ###
